# Generated by Django 3.2.9 on 2021-11-24 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0002_damaschilar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damaschilar',
            name='rozilik',
            field=models.IntegerField(choices=[(0, 'HA'), (1, 'YOQ')], default=0),
        ),
    ]
