# Generated by Django 3.2.9 on 2021-11-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0003_alter_damaschilar_rozilik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damaschilar',
            name='rozilik',
            field=models.IntegerField(choices=[(0, 'YOQ'), (1, 'HA')], default=0),
        ),
    ]
