# Generated by Django 3.2.9 on 2021-11-25 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0004_alter_damaschilar_rozilik'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamasBuyurtma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyurtmachi_ismi', models.CharField(max_length=100)),
                ('vaqti', models.DateTimeField()),
                ('haydovchi_ismi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_app.damaschilar')),
            ],
        ),
    ]
