# Generated by Django 3.2.9 on 2021-11-25 09:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0005_damasbuyurtma'),
    ]

    operations = [
        migrations.AddField(
            model_name='damasbuyurtma',
            name='sana',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='damasbuyurtma',
            name='vaqti',
            field=models.TimeField(null=True),
        ),
    ]
