# Generated by Django 3.2.9 on 2021-11-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0007_damasbuyurtma_buyurtmachi_nomeri'),
    ]

    operations = [
        migrations.CreateModel(
            name='HaydovchiBolibIshgaKirishModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('familya', models.CharField(max_length=100)),
                ('yosh', models.IntegerField()),
                ('soha', models.CharField(choices=[('yengil avto', 'yengil avto'), ('yuk avto', 'yuk avto'), ('pochta', 'pochta')], max_length=50)),
            ],
        ),
    ]
