# Generated by Django 3.2.9 on 2021-11-29 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0013_alter_gentrabuyurtma_haydovchi_ismi'),
    ]

    operations = [
        migrations.CreateModel(
            name='YukBuyurtmaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('familya', models.CharField(max_length=50)),
                ('nomer', models.CharField(max_length=50)),
                ('sana', models.DateField()),
            ],
        ),
    ]
