# Generated by Django 3.2.9 on 2021-11-29 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0014_yukbuyurtmamodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PochtaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('familya', models.CharField(max_length=50)),
                ('nomer', models.CharField(max_length=50)),
                ('viloyat', models.CharField(max_length=50)),
                ('tuman', models.CharField(max_length=50)),
                ('manzil', models.CharField(max_length=50)),
                ('yetib_borish_sana', models.DateField()),
            ],
        ),
    ]
